name: Gotchacode
description: >
    A guide to your Digital Life.
about: >
    Vinit is a Senior Backend & Systems Engineer at Socialschools B.V. His expertise lies in writing scalable backend systems in Python, Golang & Node.js. He has also written React/Backbone/Angular in many projects and has a decent understanding of mobile development.
    He enjoys solving difficult problems, debugging and coming up with simple solutions.
    At Socialschools, he has worked on APIs, performance, scaling and security of the complete application. With over 5 years of experience in Python/Django he is able to rapidly build features and debug/fix nasty bugs.

url: http://gotchacode.com
# baseurl: "/white-paper" 
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate,  jekyll-gist]

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           Vinit Kumar
  avatar:         
  email:          vinit1414.08@bitmesra.ac.in
  # Social networking links used in footer. Update and remove as you like.
  twitter:       vinitkme
  github:        vinitkumar
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  +Vinitkumarme

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-48109717-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
