name: GotchaCode
description: >
    A blog with essays about technology, programming and ethics.
about: >
  Vinit has been actively blogging since 2010 on various topics such as programming, technology,
  gadgets and software development. Consider this as a personal programming journal and enjoy the  essays if you like these topics.
master_repo: false
url: "https://gotchacode.com"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Vinit Kumar
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "mail@vinitkumar.me"
  # Social networking links used in footer. Update and remove as you like.
  twitter: vinitkme
  github: https://github.com/vinitkumar
  stackexchange: https://stackoverflow.com/users/859112/vinit-kumar?tab=profile
  linkedin: https://www.linkedin.com/in/vinitatlinkedin
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
